[package]
name = "ordinarylabs-io"
version = "0.0.0"
edition = "2021"
authors = ["sean watters <sean@ordinarylabs.io>"]

homepage = "https://ordinarylabs.io"
description = "https://ordinarylabs.io"

repository = "https://github.com/ordinarylabs/ordinary"

[dependencies]
ordinary = { workspace = true }

[workspace]
members = [
    ## only for this project
    "ordinary",

    ".extensions/git",
    ".extensions/media",
    ".extensions/payments",

    ".structure/post",
    ".structure/product",
    ".structure/user"
]

## only for this project
[workspace.dependencies]
ordinary = { path = "./ordinary", version = "*" }


[template.'*'.html]
lang = "en"
[template.'*'.html.head.meta]
charset = "utf-8"
