[package]
name = "ordinarylabs_io"
version = "0.0.0"

homepage = "https://ordinarylabs.io"
description = "https://ordinarylabs.io"

authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "ordinarylabs_io"
path = "src/main.rs"

[dependencies]
ordinary = { workspace = true }

[workspace]
members = [
    "ordinary",

    ".extensions/git",
    ".extensions/images",
    ".extensions/payments",
    ".templates/posts",
    ".templates/products",
]

[workspace.package]
authors = ["sean watters <sean@ordinarylabs.io>"]
edition = "2021"
repository = "https://github.com/ordinarylabs/ordinary"
license = "AGPL-3.0-only"

[workspace.dependencies]
ordinary = { path = "./ordinary", version = "*" }