[package]
name = "ordinarylabs-io"
version = "0.0.0"
edition = "2021"
authors = ["sean watters <sean@ordinarylabs.io>"]

homepage = "https://ordinarylabs.io"
description = "https://ordinarylabs.io"

repository = "https://github.com/ordinarylabs/ordinary"

[dependencies]
ordinary = { workspace = true }

[workspace]
members = [
    ## only for this project
    "ordinary",

    ".extensions/*",
    ".structure/*",
]

## only for this project
[workspace.dependencies]
ordinary = { path = "./ordinary", version = "*" }

[entity]
name = { type = "str" }
liked_posts = { link = "post", on = "liked_by" }

[handler.a.input]
id = { type = "str" }

[query.posts.asdf]

[expirments]

[template.'*'.html]
lang = "en"
[template.'*'.html.head.meta]
charset = "utf-8"

[ordinary]
cache = false
