[package]
name = "structure-product"
version = "0.0.0"

[cache]
# default for all structure under this route
# if not declared in nested .structure/ this
# value is used

# CCP (cascading cache policy)

[template.csv]

[properties]
